kind: Service
apiVersion: v1
metadata:
  name: reporting-service-api
  namespace: {{.Release.Namespace}}
  labels:
    app: reporting-service-api
spec:
  selector:
    app: reporting-service-api
  ports:
    - protocol: TCP
      port: {{.Values.service.port}}
      targetPort: {{.Values.service.targetPort}}
  type: ClusterIP
